apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/giomara-larraga/dockertests
  strategy:
    type: Docker                      
    dockerStrategy:
      dockerfilePath: frontend.Dockerfile    # Look for Dockerfile in: gitUri/contextDir/dockerfilePath
  output:
    to:
      kind: ImageStreamTag
      name: frontend:latest
